spring.application.name=backend


spring.datasource.url = jdbc:postgresql://localhost:5432/dailypulse
spring.datasource.username = myuser
spring.datasource.password = mypassword

spring.jpa.hibernate.ddl-auto=update
#update/create/create-drop(not in production)/validate(in production)/none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.jwt.secret=dGhpcywIsYXZlcnlTZWN1cmVTZWNyZXRLZXkxMjM0NTY=
app.jwt.expiration=86400000